<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.prelle</groupId>
  <artifactId>libterminal-jeditermfx</artifactId>
  <version>0.0.1</version>
  <name>LibTerminal-JediTermFX</name>
  <description>A pure native JavaFX Terminal component</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<javafx.version>22.0.2</javafx.version>
		<maven.compiler.target>21</maven.compiler.target>
		<maven.compiler.source>21</maven.compiler.source>
        <jeditermfx.version>1.1.0</jeditermfx.version>
    </properties>

	<dependencies>
           <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.40</version>
            </dependency>
		<dependency>
			<groupId>org.prelle</groupId>
            <artifactId>libterminal-api</artifactId>
			<version>0.0.1</version>
		</dependency>
        <dependency>
            <groupId>com.techsenger.jeditermfx</groupId>
            <artifactId>jeditermfx-core</artifactId>
            <version>${jeditermfx.version}</version>
        </dependency>
        <dependency>
            <groupId>com.techsenger.jeditermfx</groupId>
            <artifactId>jeditermfx-ui</artifactId>
            <version>${jeditermfx.version}</version>
        </dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-base</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>${javafx.version}</version>
		</dependency>
	</dependencies>
</project>