name: Compile on Windows
on: [push]
#on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  LANG: "en_EN.UTF-8"
  CENTRAL_SNAPSHOTS_TOKEN: ${{ secrets.CENTRAL_SNAPSHOTS_TOKEN }}
  OSSRH_USER_TOKEN: ${{ secrets.OSSRH_USER_TOKEN }}
  OSSRH_PWD_TOKEN: ${{ secrets.OSSRH_PWD_TOKEN }}
  DEPLOYMENT_ID: 2d8d891a-2263-4ed3-8036-a511d43d6e4f
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CC: gcc-11
  CXX: g++-11

jobs:
  compile:
    runs-on: windows-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v4

    - name: setup-graalvm-ce
      uses: gluonhq/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         # GraalVM version. Default: latest
         graalvm: 'latest'
         # Java version. Since GraalVM 22, either java11, java17 or java23. Before GraalVM 22, empty. Default: java23
         #jdk: 'java23'
         # Architecture flag. Available options are 'x86_64' (default) and 'aarch64'. The latter is available for M1 runners starting GraalVM 22.1.
         #arch: 'x86_64'

     # Setup the Windows build environment
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Visual Studio shell
      uses: egor-tensin/vs-shell@v2

    - name: Get version (bash)
      continue-on-error: true
      shell: bash -l {0}
      run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Compile dependencies
      run: mvn -U -B -s settings.xml clean install ; mkdir artifacts

    - name: Compile GraphicMUD
      run: git submodule init ; git submodule update ; cd graphicmud ; mvn -B -s ..\settings.xml clean install -D"gpg.skip" -DskipTests

    - name: Compile fat jar
      run: cd RealmRunner_CLI ; mvn -B -s ../settings.xml clean package
    - name: Compile CLI Interpreted MSI
      run: cd RealmRunner_CLI ; mvn -B -s ../settings.xml jpackage:jpackage@win
    - name: Compile CLI Native
      continue-on-error: true
      run: cd RealmRunner_CLI ; mvn -B -s ..\settings.xml gluonfx:build; ls target\

    - name: Package CLI Native
      continue-on-error: true
      run: cd RealmRunner_CLI ; mvn -B -s ..\settings.xml jpackage:jpackage@win; dir target\

    - name: Results
      run: cd RealmRunner_CLI\target ; dir ; dir dist ; dir gluonfx\x86_64-windows

    - name: Fat jar artifact
      run: |
        cp RealmRunner_CLI\target\realmrunner_cli-*with-dependencies.jar artifacts\realmrunner-cli-${{ env.RELEASE_VERSION }}.jar 
        ls -l artifacts/
    - uses: actions/upload-artifact@v4
      with:
        name: realmrunner-cli-${{ env.RELEASE_VERSION }}-JAR
        path: artifacts/realmrunner-cli-${{ env.RELEASE_VERSION }}.jar
    - uses: actions/upload-artifact@v4
      with:
        name: realmrunner-cli-${{ env.RELEASE_VERSION }}-INSTALLER
        path: artifacts/RealmRunnerCLI-${{ env.RELEASE_VERSION }}-INSTALLER.exe
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/*    